version: "3.3"
services:
    nginx:
        build: ./config/nginx
        ports:
            - "80:80"
            - "443:443"
    mariadb:
        build: ./config/mariadb
        env_file:
            - ./.env
