version: "3.3"
services:
    proxy:
        build: proxy
        restart: unless-stopped
        depends_on:
            - wordpress
        env_file:
            - .env
        ports:
            - 443:443
        volumes:
            - wordpress-data:/usr/share/nginx/html
            - adminer-data:/usr/share/nginx/adminer
        networks:
            - proxy
    wordpress:
        build: wordpress
        restart: unless-stopped
        env_file:
            - .env
        environment:
            WORDPRESS_DB_HOST: database
            WORDPRESS_DB_USER: wordpress
            WORDPRESS_DB_PASSWORD: ${MARIADB_PASSWORD}
            WORDPRESS_DB_NAME: wordpress
            WORDPRESS_TITLE: www.creedthoughts.www.gov\creedthoughts
            WORDPRESS_ADMIN_USER: vfurmane
            WORDPRESS_ADMIN_PASSWORD: ${WORDPRESS_PASSWORD}
            WORDPRESS_ADMIN_EMAIL: vfurmane@vfurmane.42.fr
            WORDPRESS_USER: honore.balzac
            WORDPRESS_EMAIL: honore.balzac@vfurmane.42.fr
            WORDPRESS_REDIS_HOST: cache
        depends_on:
            - database
        volumes:
            - wordpress-data:/var/www/html
        networks:
            - backend
            - proxy
    database:
        build: database
        restart: unless-stopped
        healthcheck:
            test: ["mysql", "--user=wordpress", "--password=${MARIADB_PASSWORD}", "-e", "SELECT 1;"]
            interval: 10s
            timeout: 10s
            retries: 3
            start_period: 20s
        env_file:
            - .env
        environment:
            MARIADB_USER: wordpress
            MARIADB_RANDOM_ROOT_PASSWORD: yes
            MARIADB_DATABASE: wordpress
        volumes:
            - wordpress-database:/var/lib/mysql
        networks:
            - backend
    cache:
        build: cache
        restart: unless-stopped
        networks:
            - backend
    ftp:
        build: ftp
        restart: unless-stopped
        env_file:
            - .env
        ports:
            - 21:21
            - 10090-10100:10090-10100
        volumes:
            - wordpress-data:/home/${FTP_USER}
    portfolio:
        build: portfolio
        restart: unless-stopped
        ports:
            - 3000:3000
    adminer:
        build: adminer
        restart: unless-stopped
        depends_on:
            - database
        volumes:
            - adminer-data:/var/www/html
        networks:
            - backend
            - proxy
    grafana:
        build: grafana
        volumes:
            - grafana-data:/var/lib/grafana
        networks:
            - backend
            - proxy
              #    nextcloud:
              #        build: nextcloud
              #        restart: unless-stopped
              #        depends_on:
              #            - database
              #        networks:
              #            - backend
              #            - proxy

volumes:
    wordpress-data:
        driver: local
        driver_opts:
            type: none
            device: /home/vfurmane/data/wordpress-data
            o: bind
    adminer-data:
        driver: local
        driver_opts:
            type: none
            device: /home/vfurmane/data/adminer-data
            o: bind
    grafana-data:
        driver: local
        driver_opts:
            type: none
            device: /home/vfurmane/data/grafana-data
            o: bind
    wordpress-database:
        driver: local
        driver_opts:
            type: none
            device: /home/vfurmane/data/wordpress-database
            o: bind
networks:
    backend:
    proxy:
